name: Eve-O Preview Release

on:
  release:
    types: [published]

jobs:
  release-windows:
    name: Release Windows
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build and publish
        run: |
          echo "Windows ${{ github.event.release.tag_name }}"
          dotnet publish src\Eve-O-Preview\Eve-O-Preview.csproj `
            -c Release `
            -o "Eve-O-Preview-${{ github.event.release.tag_name }}-Windows" `
            -p:AssemblyVersion="${{ github.event.release.tag_name }}" `
            -p:FileVersion="${{ github.event.release.tag_name }}" `
            --self-contained false

      - name: Create archive
        run: |
          Compress-Archive -Path "Eve-O-Preview-${{ github.event.release.tag_name }}-Windows\*" -DestinationPath "Release-${{ github.event.release.tag_name }}-Windows.zip"

      - name: Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: Release-${{ github.event.release.tag_name }}-Windows.zip
